FROM golang:1.14.4-alpine

RUN apk add --no-cache \
    ca-certificates \
    git \
    make \
    gcc \
    libc-dev \
    && go get -u github.com/cosmtrek/air \
    && go get -u github.com/yyh-gl/realize \
    && go get -u github.com/golangci/golangci-lint/cmd/golangci-lint \
    && go get -u github.com/google/wire/cmd/wire \
    && go get -u github.com/tj/robo
