# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "make build target=rest version=local"
# Binary file yields from `cmd`.
bin = "cmd/rest/bin/api-server"
# Customize binary.
full_bin = "cmd/rest/bin/api-server"
# Watch these filename extensions.
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = ["docker", "app/presentation/cli", "app/presentation/graphql"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = ["cmd/rest/wire_gen.go", "cmd/cli/wire_gen.go", "test/wire_gen.go"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop to run old binary when build errors occur.
stop_on_error = true
# This log file places in your tmp_dir.
log = "logs/air_errors.log"

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
