version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - govet
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
