run:
  tests: true
  timeout: 5m
  skip-files:
    # FIXME: I don't know why this file (golang/go's file) is target. I skip this file in temporary.
    - sort.go

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - errcheck

issues:
  exclude-use-default: false
