# OktetoはIngressのみサポート（LoadBalancerをサポートしていない）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    dev.okteto.com/generate-host: "true"
  name: hobigon-api-ingress
  namespace: hobigon-yyh-gl
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hobigon-api-service
            port:
              number: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: hobigon-api-service
  namespace: hobigon-yyh-gl
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: hobigon-api
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobigon-api-deployment
  labels:
    app: hobigon-api
  namespace: hobigon-yyh-gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobigon-api
  template:
    metadata:
      labels:
        app: hobigon-api
      namespace: hobigon-yyh-gl
    spec:
      containers:
        - name: hobigon-api
          image: ghcr.io/yyh-gl/hobigon-golang-api-server/prd/hobigon-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_PATH
              value: "/tmp"
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_host
                  optional: false
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_port
                  optional: false
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_database
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_user
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
                  optional: false
