apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: hobigon-yyh-gl
spec:
  storageClassName: okteto-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: hobigon-yyh-gl
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Hobigon Prometheus
        type: prometheus
        url: http://prometheus-service:9090
        is_default: true
  grafana.ini: |
    [server]
    root_url = https://grafana-service-hobigon-yyh-gl.cloud.okteto.net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: hobigon-yyh-gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      namespace: hobigon-yyh-gl
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana
              readOnly: false
            - name: grafana-config-volume
              mountPath: /etc/grafana/
              readOnly: true
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      securityContext:
        runAsUser: 472
        fsGroup: 472
      volumes:
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: grafana-pv-claim
        - name: grafana-config-volume
          configMap:
            name: grafana-config
            defaultMode: 420
            items:
              - key: grafana.ini
                path: grafana.ini
        - name: grafana-datasources
          configMap:
            name: grafana-config
            defaultMode: 420
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
        
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: hobigon-yyh-gl
  annotations:
    dev.okteto.com/auto-ingress: "private"
spec:
  type: ClusterIP
  ports:
    - name: grafana
      port: 9091
      targetPort: 3000
  selector:
    app: grafana
