# Oktetoの自動スリープ対策
# okteto.ymlを反映したあとでapi.ymlを反映することでスリープ防止
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobigon-api-deployment
  labels:
    app: hobigon-api
  namespace: hobigon-yyh-gl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hobigon-api
  template:
    metadata:
      labels:
        app: hobigon-api
      namespace: hobigon-yyh-gl
    spec:
      containers:
        - name: hobigon-api
          image: ghcr.io/yyh-gl/hobigon-golang-api-server/rest:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_PATH
              value: "/tmp"
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_host
                  optional: false
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_port
                  optional: false
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_database
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_user
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
                  optional: false
            - name: TRELLO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: trello_api_key
                  optional: false
            - name: TRELLO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: trello_api_token
                  optional: false
            - name: MAIN_BOARD_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: main_board_id
                  optional: false
            - name: TECH_BOARD_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: tech_board_id
                  optional: false
            - name: WORK_BOARD_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: work_board_id
                  optional: false
            - name: MAIN_WIP_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: main_wip_list_id
                  optional: false
            - name: TECH_WIP_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: tech_wip_list_id
                  optional: false
            - name: WORK_WIP_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: trello-secret
                  key: work_wip_list_id
                  optional: false
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: slack_api_token
                  optional: false
            - name: WEBHOOK_URL_TO_00
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook_url_to_00
                  optional: false
            - name: WEBHOOK_URL_TO_02
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook_url_to_02
                  optional: false
            - name: WEBHOOK_URL_TO_50
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook_url_to_50
                  optional: false
            - name: WEBHOOK_URL_TO_51
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook_url_to_51
                  optional: false
            - name: WEBHOOK_URL_TO_SHINSOTSU
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook_url_to_shinsotsu
                  optional: false
