apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: hobigon-yyh-gl
data:
  prometheus.rules: |-
    groups:
    - name: alert
      rules:
      - alert: High Count
        expr: sum(hobigon_request_count) > 10
        for: 1m
        annotations:
          summary: High Count Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'go-prometheus-monitoring'
        static_configs:
        - targets:
          - hobigon-api-service:3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: hobigon-yyh-gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      namespace: hobigon-yyh-gl
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: hobigon-yyh-gl
  annotations:
    dev.okteto.com/auto-ingress: "private"
    prometheus.io/scrape: "true"
    prometheus.io/port:   "9090"
spec:
  type: ClusterIP
  ports:
    - name: "prometheus"
      port: 9090
  selector:
    app: prometheus
