// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	Title string `json:"title"`
	Count int    `json:"count"`
}

type Mutation struct {
}

type NewBlog struct {
	Title string `json:"title"`
}

type Query struct {
}
