name: Deployment

on:
  push:
    tags:
      - 'v[1-9]+.[0-9]+.[0-9]+'

jobs:
  create_release_note:
    name: Create release note
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Make release note
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_container_image_specified_version:
    name: Publish container image (specified version)
    runs-on: ubuntu-latest
    needs: create_release_note
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set VERSION environment
        env:
          REF: ${{ github.ref }}
        run: echo "VERSION=${REF##*/}" >> $GITHUB_ENV
      - name: Set TAG environment
        run: echo "TAG=${{ secrets.CONTAINER_REGISTORY }}/${{ github.repository }}/rest:${{ env.VERSION }}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTORY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GCR_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/rest/Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  
  publish_container_image_latest_version:
    name: Publish container image (latest version)
    runs-on: ubuntu-latest
    needs: create_release_note
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set VERSION environment
        env:
          REF: ${{ github.ref }}
        run: echo "VERSION=${REF##*/}" >> $GITHUB_ENV
      - name: Set TAG environment
        run: echo "TAG=${{ secrets.CONTAINER_REGISTORY }}/${{ github.repository }}/rest:latest" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTORY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GCR_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/rest/Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy_to_k8s:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    needs: [ create_release_note, publish_container_image_specified_version ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set VERSION environment
        env:
          REF: ${{ github.ref }}
        run: echo "VERSION=${REF##*/}" >> $GITHUB_ENV
      - name: Set TAG environment
        run: echo "TAG=${{ secrets.CONTAINER_REGISTORY }}/${{ github.repository }}/rest:${{ env.VERSION }}" >> $GITHUB_ENV
      - name: Set Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image -n hobigon deployment/hobigon-api-deployment hobigon-api=${{ env.TAG }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set VERSION environment
        env:
          REF: ${{ github.ref }}
        run: echo "VERSION=${REF##*/}" >> $GITHUB_ENV
      - name: Build
        run: make build-all version=${{ env.VERSION }}
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ./cmd/rest/bin/api-server
            ./cmd/cli/bin/hobi
            ./cmd/graphql/bin/graphql-server
          retention-days: 1
          if-no-files-found: error

  success_notification:
    name: Success notification
    needs: [ publish_container_image_latest_version, deploy_to_k8s ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_TITLE: CD Success
        if: env.WORKFLOW_CONCLUSION == 'success'

  failure_notification:
    name: Failure notification
    needs: [ publish_container_image_latest_version, deploy_to_k8s ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_TITLE: CD Failure
          SLACK_COLOR: danger
        if: env.WORKFLOW_CONCLUSION == 'failure'
