name: Wake-up-Okteto

on:
  workflow_dispatch:
  schedule:
    # 12時間ごとに実行
    - cron: '0 */12 * * *'

jobs:
  wake_up_okteto:
    name: Wake up Okteto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Apply fake manifest
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./k8s/okteto.yml
      - name: Apply real manifest
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./k8s/api.yml
