name: Wake-up-Okteto-2

on:
  workflow_dispatch:
  schedule:
    # AM5:00(JST)に実行
    - cron: '0 21 * * *'

jobs:
  wake_up_okteto:
    name: Wake up Okteto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Apply real manifest
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./k8s/api.yml
